<?php

namespace Database\Seeders;

use App\Models\Products;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Products::create([
            'name'=>'Product 02',
            'user_id'=>3,
            'category_id'=>1,
            'photos'=>"",
            'thumbnail_img'=>"",
            'tags'=>0,
            'description'=>"",
            'unit_price'=>58000,
            'purchase_price'=>0.00,
            'variant_product'=>0,
            'attributes'=>"[]",
            'choice_options'=>"[]",
            'approved'=>0,
            'current_stock'=>30000,
            'unit'=>"KG",
            'weight'=>1,
            'min_qty'=>1,
            'low_stock_quantity'=>1,
            'discount'=>0.00,
            'discount_type'=>"amount",
            'discount_start_date'=>"",
            'discount_end_date'=>"",
            'shipping_type'=>"free",
            'est_shipping_days'=>1,
            'num_of_sale'=>0,
            'meta_img'=>"",
            'slug'=>"product_02",
            'rating'=>0.00,
            'published'=>1,
        ]);

        Products::create([
            'name'=>'Product 03',
            'user_id'=>3,
            'category_id'=>1,
            'photos'=>"",
            'thumbnail_img'=>"",
            'tags'=>0,
            'description'=>"",
            'unit_price'=>68000,
            'purchase_price'=>0.00,
            'variant_product'=>0,
            'attributes'=>"[]",
            'choice_options'=>"[]",
            'approved'=>0,
            'current_stock'=>30000,
            'unit'=>"KG",
            'weight'=>2,
            'min_qty'=>1,
            'low_stock_quantity'=>1,
            'discount'=>0.00,
            'discount_type'=>"amount",
            'discount_start_date'=>"",
            'discount_end_date'=>"",
            'shipping_type'=>"free",
            'est_shipping_days'=>1,
            'num_of_sale'=>0,
            'meta_img'=>"",
            'slug'=>"product_03",
            'rating'=>0.00,
            'published'=>1,
        ]);

        Products::create([
            'name'=>'Product 04',
            'user_id'=>3,
            'category_id'=>1,
            'photos'=>"",
            'thumbnail_img'=>"",
            'tags'=>0,
            'description'=>"",
            'unit_price'=>28000,
            'purchase_price'=>0.00,
            'variant_product'=>0,
            'attributes'=>"[]",
            'choice_options'=>"[]",
            'approved'=>0,
            'current_stock'=>30000,
            'unit'=>"KG",
            'weight'=>1,
            'min_qty'=>1,
            'low_stock_quantity'=>1,
            'discount'=>0.00,
            'discount_type'=>"amount",
            'discount_start_date'=>"",
            'discount_end_date'=>"",
            'shipping_type'=>"free",
            'est_shipping_days'=>1,
            'num_of_sale'=>0,
            'meta_img'=>"",
            'slug'=>"product_04",
            'rating'=>0.00,
            'published'=>1,
        ]);

        Products::create([
            'name'=>'Product 05',
            'user_id'=>3,
            'category_id'=>1,
            'photos'=>"",
            'thumbnail_img'=>"",
            'tags'=>0,
            'description'=>"",
            'unit_price'=>18000,
            'purchase_price'=>0.00,
            'variant_product'=>0,
            'attributes'=>"[]",
            'choice_options'=>"[]",
            'approved'=>0,
            'current_stock'=>30000,
            'unit'=>"KG",
            'weight'=>1,
            'min_qty'=>1,
            'low_stock_quantity'=>1,
            'discount'=>0.00,
            'discount_type'=>"amount",
            'discount_start_date'=>"",
            'discount_end_date'=>"",
            'shipping_type'=>"free",
            'est_shipping_days'=>1,
            'num_of_sale'=>0,
            'meta_img'=>"",
            'slug'=>"product_05",
            'rating'=>0.00,
            'published'=>1,
        ]);

        Products::create([
            'name'=>'Product 06',
            'user_id'=>3,
            'category_id'=>1,
            'photos'=>"",
            'thumbnail_img'=>"",
            'tags'=>0,
            'description'=>"",
            'unit_price'=>108000,
            'purchase_price'=>0.00,
            'variant_product'=>0,
            'attributes'=>"[]",
            'choice_options'=>"[]",
            'approved'=>0,
            'current_stock'=>30000,
            'unit'=>"KG",
            'weight'=>1,
            'min_qty'=>1,
            'low_stock_quantity'=>1,
            'discount'=>0.00,
            'discount_type'=>"amount",
            'discount_start_date'=>"",
            'discount_end_date'=>"",
            'shipping_type'=>"free",
            'est_shipping_days'=>1,
            'num_of_sale'=>0,
            'meta_img'=>"",
            'slug'=>"product_06",
            'rating'=>0.00,
            'published'=>1,
        ]);

        Products::create([
            'name'=>'Product 07',
            'user_id'=>3,
            'category_id'=>1,
            'photos'=>"",
            'thumbnail_img'=>"",
            'tags'=>0,
            'description'=>"",
            'unit_price'=>39000,
            'purchase_price'=>0.00,
            'variant_product'=>0,
            'attributes'=>"[]",
            'choice_options'=>"[]",
            'approved'=>0,
            'current_stock'=>30000,
            'unit'=>"KG",
            'weight'=>1,
            'min_qty'=>1,
            'low_stock_quantity'=>1,
            'discount'=>0.00,
            'discount_type'=>"amount",
            'discount_start_date'=>"",
            'discount_end_date'=>"",
            'shipping_type'=>"free",
            'est_shipping_days'=>1,
            'num_of_sale'=>0,
            'meta_img'=>"Product 01",
            'slug'=>"product_07",
            'rating'=>0.00,
            'published'=>1,
        ]);

        Products::create([
            'name'=>'Product 08',
            'user_id'=>3,
            'category_id'=>1,
            'photos'=>"",
            'thumbnail_img'=>"",
            'tags'=>0,
            'description'=>"",
            'unit_price'=>12000,
            'purchase_price'=>0.00,
            'variant_product'=>0,
            'attributes'=>"[]",
            'choice_options'=>"[]",
            'approved'=>0,
            'current_stock'=>30000,
            'unit'=>"KG",
            'weight'=>1,
            'min_qty'=>1,
            'low_stock_quantity'=>1,
            'discount'=>0.00,
            'discount_type'=>"amount",
            'discount_start_date'=>"",
            'discount_end_date'=>"",
            'shipping_type'=>"free",
            'est_shipping_days'=>1,
            'num_of_sale'=>0,
            'meta_img'=>"",
            'slug'=>"product_08",
            'rating'=>0.00,
            'published'=>1,
        ]);
    }
}
